terminology=[
    [[5,"are"],[2,"are","r","ar"]],
    [[5,"you"],[2,"you","u","ya"]],
    [[5,"hello"],[2,"hello","helo","yo"]],
    [[5,"doing"],[2,"doing","doin"]],
    [[5,"what"],[2,"what","wut","wat"]],
    [[5,"and"],[3,"and","&"]],
    [[5,"got to","have to"],[3,"gotta","have to"],[1,"goda","gota"]],
    [[5,"with"],[2,"with","w/","wis","wiz"]],
    [[5,"very","pretty"],[4,"very"],[3,"very","soo"],[2,"fucking","fuckin","goddam"]],
    [[5,"one"],[2,"one","1"]],
    [[5,"my"],[2,"my","ma"]],
    [[5,"thats", "that is"],[1,"that"]],
    [[5,"mate"],[2,"mate","m8"]],
    [[5,"can not","cannot","cant"],[4,"cannot","cant"],[2,"cant"]],
    [[5,"do not","dont"],[3,"dont"]],
    [[5,"likes"],[2,"likes","like","lik"]],
    [[5,"because"],[3,"because","cuz","cus","becuz"]],
    [[5,"its"],[2,"its","itz"],[1,"it"]],
    [[5,"youre"],[3,"your"],[2,"ur","yur","your"]],
    [[5,"may"],[3,"can"]],
    [[5,"love"],[2,"love","luv","❤️"]],
    [[5,"yours"],[3,"urs","yours"],[2,"urs"]],
    [[5,"is"],[2,"is","iz",""]],
    [[5,"ok"],[4,"ok","fine"]],
    [[5,"no"],[2,"nah","no"]],
    [[5,"oh"],[2,"oh","aw"]],
    [[5,"see you"],[3,"cya","see you"]],
    [[5,"hi","hello"],[3,"hi","hey"]],
    [[5,"insane"],[2,"insane","sane"]],
    [[5,"about"],[2,"about","abt","abut"]],
    [[5,"the"],[2,"the","da","le"]],
    [[5,"not"],[2,"aint"]],
    [[5,"alright", "all right"],[2,"alright","aight"]],
    [[5,"my"],[2,"my","ma"]],
    [[5,""],[2,""]]]
omissions=[
    [["youre","your"],"dont","cant","its","musnt","aint","shouldnt","couldnt"],
    ["you're","don't","can't","it's","musn't","ain't","shouldn't","aren't","couldn't"],
    ["you are","do not","can not","it is","must not","ain't","should not","are not","could not"]]
maturity=[["fuck","frick","f**k","f*ck","f***","fk","fck"],["damn","dam","d*mn"],["darn","d*rn"],["shit","sh*t","sh**","sh","sht"],["ass","a**","a$$"],["dick","d**k","d*ck"],["cum","c*m"],["slut","sl*t"],["whore","wh*re"],["hoes","ho*s","h**s"]]
